### ISSUE TITLE
Question: Browserify not included in package dependencies

### ISSUE THREAD

**Issue by Daniel-Yonkov** [digitalmaas/serverless-plugin-browserifier#33]
Hello there,
Noticed an inconsistency during the migration of the no longer supported `serverless-plugin-browserify` plugin to this one. Seems like they included a version of browserify in their dependencies while this package does not.

Is this intended in order to allow customization of the browserify version or is there any other reason behind not including the package within the plugin?

**Comment by nolde** [comment]
Hello!

Yes, the goal is to allow you to upgrade browserify as soon as it is available.

**Comment by otaviolm** [comment]
Hello there, 

Now node 14 version is available to use on AWS lambda, I'm trying to use a feature from this version [optional chaining](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Optional_chaining), however I'm facing a error when I try to use serverless-plugin-browserifier, without this plugin it's possible to compile code.

This is the error: "OperationalError: Parsing file {path}: Unexpected token (32:27)"

Is the plugin compatible with node 14 version ?
