### ISSUE TITLE
Optional chaining is not working with serverless-plugin-browserifier

### ISSUE THREAD

**Issue by otaviolm** [digitalmaas/serverless-plugin-browserifier#36]
Hello there,

Now node 14 version is available to use on AWS lambda, I'm trying to use a feature from this version [optional chaining](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Optional_chaining), however I'm facing a error when I try to use serverless-plugin-browserifier, without this plugin it's possible to compile code.

This is the error: "OperationalError: Parsing file {path}: Unexpected token (32:27)"

Is the plugin compatible with node 14 version ?

**Comment by nolde** [comment]
Hello @otaviolm ,

Yeah, I'm using it along with node 14 without any issues. I use optional chaining, null coalescing and all bells and whistles I can find.
